---
- name: Install node and npm
  hosts: all
  become: yes
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install node and npm
      apt: 
        pkg: 
          - nodejs
          - npm
          - unzip
    - name: Create directory for download
      file:
        path: /tmp/nodejs_app
        state: directory
    - name: Download ZIP archive
      get_url:
        url: "https://gitlab.com/devops-bootcamp3/simple-nodejs/-/archive/master/simple-nodejs-master.zip"
        dest: /tmp/nodejs_app/simple-nodejs-master.zip
    - name: Unarchive ZIP on remote machine
      command: unzip -o /tmp/nodejs_app/simple-nodejs-master.zip -d /tmp/nodejs_app/
    - name: Install the dependencies
      npm:
        path: /tmp/nodejs_app/simple-nodejs-master  
    - name: Start the application
      command:
        chdir: /tmp/nodejs_app/simple-nodejs-master/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
